isClusterService: false
servers:
- zones:
  - zone: .
  port: 53
  # If serviceType is nodePort you can specify nodePort here
  # nodePort: 30053
  plugins:
  - name: log
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  # Required to query kubernetes API for data
  #- name: kubernetes
  #  parameters: cluster.local in-addr.arpa ip6.arpa
  #  configBlock: |-
  #    pods insecure
  #    fallthrough in-addr.arpa ip6.arpa
  #    ttl 30
  # Serves a /metrics endpoint on :9153, required for serviceMonitor
  #- name: prometheus
  #  parameters: 0.0.0.0:9153
  #- name: forward
  #  parameters: . /etc/resolv.conf
  #- name: cache
  #  parameters: 30
  #- name: loop
  - name: reload
  - name: loadbalance
  # Addition for local test
  - name: etcd
    parameters: example-foo4567.com
    configBlock: |-
      stubzones
      path /skydns
      #endpoint http://etcd-test-only-headless.default.svc.cluster.local:2379
      endpoint http://10.244.0.15:2379
