apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: default
spec:
  controllerName: "github.com/tv2/cloud-gateway-controller"
  parametersRef:
    group: v1
    kind: ConfigMap
    name: default-gateway-class
    namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-gateway-class
  namespace: default
data:
  tier2GatewayClass: istio
  albTemplate:
    apiVersion: elbv2.aws.crossplane.io/v1alpha1
    kind: LoadBalancer
    metadata:
      name: aws-alb-test
    spec:
      providerConfigRef:
        name: admin
      forProvider:
        name: aws-alb-test
        region: eu-central-1
        securityGroups:
          - $SG_ID
        subnetMappings:
          - subnetID: $SUBNET1
          - subnetID: $SUBNET2
          - subnetID: $SUBNET3
