# permissions for end users to view gatewayclassparameters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayclassparameters-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gateway-controller
    app.kubernetes.io/part-of: gateway-controller
    app.kubernetes.io/managed-by: kustomize
  name: gatewayclassparameters-viewer-role
rules:
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassparameters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.tv2.dk
  resources:
  - gatewayclassparameters/status
  verbs:
  - get
