apiVersion: gateway.tv2.dk/v1alpha1
kind: GatewayClassConfig
metadata:
  name: aws-alb-crossplane-public
  namespace: bifrost-gateway-controller-system
  annotations:
    krm-apply-setters: "true"
spec:
  override:
    region: eu-central-1
    vpcId: "vpc-0f0a7248b68315eb0" # kpt-set: ${vpcId}
    subnets: # kpt-set: ${publicSubnetIds}
      - subnet-02d99e9a066281659
      - subnet-06f748b0455d254af
      - subnet-0598d5f99b6958758
    upstreamSecurityGroup: "sg-0a4c4eb536ac8bb09" # kpt-set: ${clusterNodeSecurityGroupId}
    internal: false
    tags:
      bifrost-gateway-controller/gatewayclass: aws-alb-crossplane-public
  targetRef:
    group: gateway.networking.k8s.io
    kind: GatewayClass
    name: aws-alb-crossplane-public
