apiVersion: gateway.tv2.dk/v1alpha1
kind: GatewayClassConfig
metadata:
  name: foo-infra-tenant-defaults
  namespace: foo-infra
spec:
  override:
    certificateArn: arn:aws:acm:eu-central-1:123456789012:certificate/33ce4a38-aff0-4ad7-bc7c-275fe99556e1
    tags:
      tenant: foo-tenant
  targetRef:
    group: ""
    kind: Namespace
    name: foo-infra
