apiVersion: gateway.tv2.dk/v1alpha1
kind: GatewayClassConfig
metadata:
  name: foo-infra-tenant-defaults
  namespace: foo-infra
spec:
  override:
    certificateArn: $CERTIFICATE_ARN
    tags:
      tenant: foo-tenant
  targetRef:
    group: ""
    kind: Namespace
    name: foo-infra
