apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-controller.fullname" . }}-manager-metrics-service
  labels:
    control-plane: manager
    {{- include "gateway-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    control-plane: manager
    {{- include "gateway-controller.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.prometheus.service.port }}
    protocol: TCP
