apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: foo-gateway
  namespace: foo-infra
spec:
  gatewayClassName: $GATEWAY_CLASS_NAME
  listeners:
  - name: web
    port: 80
    protocol: HTTP
    hostname: $DOMAIN
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            allowGateway: foo
