name: Test / Release

on:
  pull_request:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run tests
        run: |
          make test


  # This is PR builds
  build-pr:
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    needs: ["tests"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      # Use goreleaser snapshot builds for PR builds to avoid duplication
      # This is a bit convoluted - see also goreleaser nightly builds feature

      - name: Downcase repository if it has upper case chars
        run: |
          echo "REGISTRY=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Get SHA that triggered PR
        run: |
          echo -n "HEAD_SHA=" >>${GITHUB_ENV}
          git rev-parse --short "${{ github.event.pull_request.head.sha }}" >>${GITHUB_ENV}

      - name: Make PR build
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist --snapshot
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List PR images
        run: |
          docker image ls --format "{{.Repository}}:{{.Tag}}" | \
            grep -ie "${{ github.repository}}:.*${HEAD_SHA}.*" | \
            paste -sd ' ' /dev/stdin > images

      - name: Push PR images
        run: |
          cat images | xargs -d ' ' -I{} -n1 sh -c "docker push {}"

      - name: Create and push manifest for PR images tag
        run: |
          docker manifest create $REGISTRY:sha-$HEAD_SHA $(cat images)
          docker manifest push $REGISTRY:sha-$HEAD_SHA


  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: ["tests"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      # To be compatible with ENVs in PRs
      - name: Get SHA that triggered release
        run: |
          echo -n "HEAD_SHA=" >>${GITHUB_ENV}
          git rev-parse --short $GITHUB_SHA >>${GITHUB_ENV}

      - name: Make release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
